### ISSUE TITLE
something went wrong...

### ISSUE THREAD

**Issue by Igor-A1** [ubavic/mobius-shader#1]
i'm copy glsl source to https://thebookofshaders.com but I got a different picture than yours png
result not has any spirals after playing. only circles :(  

https://observablehq.com/@igor-a1/mobius-shader

**Comment by ubavic** [comment]
Hello Igor.

Yeah, the image I provided in `README` is a little bit misleading (I will put some note to fix that). I wanted to present what is the shader capable of doing (with minimal modification), but I also wanted to keep code as simple as possible and self-explanatory. So code doesn't render provided image :D

If you want to render spirals try to change function `dartboard` in a following way (only the `if` statement is changed):

```glsl
vec4 dartboard(vec2 a) {
    float r = 2.0 * log(length(a));
    float t = 8.0 * atan(a.y, a.x) / PI;
    
    if (mod(floor(r - 0.5 * t) + floor(t + 0.5 * r), 2.0) > 0.0)
        return color_light;
    else
        return color_dark;
}
```

Experiment with different coefficients for different visual effects (eg. try using `mod(floor(r - 1.5 *t) + floor(t + 2.5 * r ), 2.0)` or `mod(floor(r - 2.5 *t) + floor(t + 2.5 * r ), 2.0)`, etc....).

**Comment by Igor-A1** [comment]
Great! It's working right :) Added some opts in my [observable notebook](https://observablehq.com/@igor-a1/mobius-shader) too...
Many thanks with best regards!
